//Login
export const INICIAR_SESION = 'INICIAR_SESION'
export const CERRAR_SESION = 'CERRAR_SESION'


//Common
export const SHOW_MODAL = 'SHOW_MODAL'
export const MOSTRAR_MENSAJE = 'MOSTRAR_MENSAJE'
export const LIMPIAR_MENSAJES = 'LIMPIAR_MENSAJES'
export const MOSTRAR_MESSAGE_BOX = 'MOSTRAR_MESSAGE_BOX'
export const MOSTRAR_MESSAGE_INFO_BOX = 'MOSTRAR_MESSAGE_INFO_BOX'


//Usarios
export const GET_USERS = 'GET_USERS'
export const SELECCIONAR_USUARIO = 'SELECCIONAR_USUARIO'
export const NEW_USUARIO = 'NEW_USUARIO'
export const CHANGE_ATTR_USUARIO = 'CHANGE_ATTR_USUARIO'
export const CLEAN_USUARIO = 'CLEAN_USUARIO'


//Clientes
export const GET_CLIENTES = 'GET_CLIENTES'
export const SELECCIONAR_CLIENTE = 'SELECCIONAR_CLIENTE'
export const NEW_CLIENTE = 'NEW_CLIENTE'
export const CHANGE_ATTR_CLIENTE = 'CHANGE_ATTR_CLIENTE'
export const CLEAN_CLIENTE = 'CLEAN_CLIENTE'
export const EDIT_CLIENTE = 'EDIT_CLIENTE'


//Parametros
export const GET_PARAMETROS = 'GET_PARAMETROS'
export const SELECCIONAR_PARAMETRO = 'SELECCIONAR_PARAMETRO'
export const NEW_PARAMETRO = 'NEW_PARAMETRO'
export const CHANGE_ATTR_PARAMETRO = 'CHANGE_ATTR_PARAMETRO'
export const CLEAN_PARAMETRO = 'CLEAN_PARAMETRO'
