//Login
export const INICIAR_SESION = 'INICIAR_SESION'
export const CERRAR_SESION = 'CERRAR_SESION'


//Common
export const SHOW_MODAL = 'SHOW_MODAL'
export const MOSTRAR_MENSAJE = 'MOSTRAR_MENSAJE'
export const LIMPIAR_MENSAJES = 'LIMPIAR_MENSAJES'
export const MOSTRAR_MESSAGE_BOX = 'MOSTRAR_MESSAGE_BOX'
export const MOSTRAR_MESSAGE_INFO_BOX = 'MOSTRAR_MESSAGE_INFO_BOX'


//Usarios
export const GET_USERS = 'GET_USERS'
export const SELECCIONAR_USUARIO = 'SELECCIONAR_USUARIO'
export const NEW_USUARIO = 'NEW_USUARIO'
export const CHANGE_ATTR_USUARIO = 'CHANGE_ATTR_USUARIO'

